version: '3.4'

services:
  pokedex:
    image: pokedex
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19003:19003
      - 19004:19004
      - 19005:19005